### ISSUE TITLE
ERROR when no scrub status is available

### ISSUE THREAD

**Issue by ANeumann82** [iwvelando/telegraf-exec-btrfs-status#1]
Just compiled and ran the tool on a btrfs I moved from my old system. The output of `btrfs scrub status` is:
```
btrfs scrub status -d /mnt/btrfs/
UUID:             867f18ed-aaaa-aaaa-aaaa-c4492fb3049d

Scrub device /dev/sda (id 4)
        no stats available

Scrub device /dev/sdc (id 5)
        no stats available

Scrub device /dev/sdd (id 6)
        no stats available

Scrub device  (id 7)
        no stats available

Scrub device /dev/sdb (id 8)
        no stats available

Scrub device /dev/sdf (id 9)
        no stats available

Scrub device /dev/sde (id 10)
        no stats available
```

And in the console I got this error:
```
ERRO[0000] failed to parse btrfs scrub status -d /mnt/btrfs  error="failed to parse scrub start time; parsing time \"\" as \"Mon Jan 2 15:04:05 2006\": cannot parse \"\" as \"Mon\"" op=main.ParseBtrfsScrubStatus
```

Some things to notice:
- One device is missing (id 7)
- No Scrub has ran on this system yet.

I may get around to fix this myself, if I feel like getting into go again, but at least wanted to let you know.

**Comment by iwvelando** [comment]
Thanks for reporting this. If I get some time I'll try and incorporate this into the template. I wish btrfs provided machine output for all of its descriptive commands :)

**Comment by iwvelando** [comment]
I was curious about the circumstances that led to your output so I wanted to see what would happen with a bare btrfs filesystem:

```
$ sudo btrfs scrub status /dev/loop3
UUID:             67a5a9ae-4378-4280-a6f5-39ba0a518660
        no stats available
Total to scrub:   352.00KiB
Rate:             0.00B/s
Error summary:    no errors found
```

This is Ubuntu 22.04 with btrfs-progs v5.16.2, and the output is rather different still. Out of curiosity what OS version/btrfs progs version are you running? `cat /etc/*-release` and `btrfs --version` should provide that.

Regardless, my thinking is that these outputs lack useful quantitative data and I think the program would be better to cleanly exit without emitting any line protocol rather than either throw logs (as that would become noise rapidly given the nature of how this is expected to be run i.e. through telegraf exec) or set default values.

If you have time please take a look at https://github.com/iwvelando/telegraf-exec-btrfs-status/pull/2 and let me know what you think. I've validated that it's not a regression on my Ubuntu/btrfs progs/filesystem combination at least. I'm looking at that as a first step; I think there are a lot of ways this program should be revised now that I have a lot more experience but I don't currently have time to implement those.

**Comment by iwvelando** [comment]
I've gone ahead and merged that. If you'd like to get the tool behaving differently on the current state of your setup feel free we can continue the conversation -- in that case I'd ask to include the OS release `cat /etc/*-release` and the BTRFS version `btrfs --version` in case that differs from the versions I developed the tool for.
